name: tiendavictoria
display_name: Tienda Victoria
version: 1.0.0
author:
  name: cepardov & Bonpresta
  email: 
  url: https://cepardov.cl
meta:
  compatibility:
    from: 1.7.0.0
    to: ~
  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-both-columns:
      name: Three Columns
      description: One large central column and 2 side columns.
    layout-left-column:
      name: Two Columns, small left column
      description: Two columns with a small left column
    layout-right-column:
      name: Two Columns, small right column
      description: Two columns with a small right column


global_settings:
  configuration:
    PS_IMAGE_QUALITY: png
  modules:
    to_disable:
      - productcomments
      - blockwishlist
    to_enable:
      - bonask
      - bonattribute
      - bonbanner
      - bonbannermenu
      - bonbrand
      - boncall
      - boncart
      - boncollection
      - boncomments
      - boncompare
      - bongdpr
      - bongooglemap
      - bongooglepay
      - bonhtmlcontent
      - boninfoban
      - boninstagram
      - bonloginfacebook
      - bonnews
      - bonnewsletter
      - bonnotice
      - bonorder
      - bonportfolio
      - bonpromotion
      - bonsearch
      - bonslick
      - bontab
      - bontheme
      - bonthumbnails
      - bonwhatsappchat
      - bonwishlist
      - bonzoom
      - customtab
      - facebookwidget
      - productbutton
      - productcountdown
      - productpurchase
      - productyoutube
      - psgdpr
      - zendeskchat
  hooks:
    modules_to_hook:
      displayAfterBodyOpeningTag:
        - bonnotice
      displayAttributeButton:
        - bonattribute
      displayAttributeForm:
        - ps_facetedsearch
      displayAttributeGroupForm:
        - ps_facetedsearch
      displayAttributeGroupPostProcess:
        - ps_facetedsearch
      displayBackOfficeHeader:
        - bonhtmlcontent
        - bonbanner
        - productcountdown
        - productyoutube
        - bonpromotion
        - customtab
        - bontab
        - bonslick
        - bongooglemap
        - bonbannermenu
        - productpurchase
        - bonwhatsappchat
        - boninfoban
        - bongooglepay
        - boncollection
        - bonportfolio
        - bonnews
        - boninstagram
      displayBeforeBodyClosingTag:
        - bonzoom
        - productcountdown
        - bonwishlist
        - bonask
        - productpurchase
        - bongooglepay
        - boncompare
        - bonloginfacebook
      displayBonAttribute:
        - bonattribute
      displayBonCart:
        - boncart
      displaybonCompare:
        - boncompare
      displayBonInstagram:
        - boninstagram
      displayBonLogFacebook:
        - bonloginfacebook
      displayBonLogFacebookimg:
        - bonloginfacebook
      displayBonWishlist:
        - bonwishlist
      displayCustomBanner:
        - bonnotice
        - bongdpr
      displayCustomBannerMenu:
        - bonbannermenu
      displayCustomerAccount:
        - psgdpr
      displayCustomSlick:
        - bonslick
        - bonbanner
      displayCustonBoncollection:
        - boncollection
      displayCustonBonportfolio:
        - bonportfolio
      displayFeatureForm:
        - ps_facetedsearch
      displayFeaturePostProcess:
        - ps_facetedsearch
      displayFeatureValueForm:
        - ps_facetedsearch
      displayFeatureValuePostProcess:
        - ps_facetedsearch
      displayFooter:
        - ps_contactinfo
        - ps_socialfollow
        - ps_linklist
        - ps_customeraccountlinks
        - ps_emailsubscription
        - bonorder
        - bonwhatsappchat
      displayFooterBefore:
        - bonhtmlcontent
      displayFooterProduct:
        - ps_categoryproducts
      displayGDPRConsent:
        - psgdpr
      displayGoogleMap:
        - bongooglemap
      displayGridButton:
        - bontheme
      displayHome:
        - ps_featuredproducts
        - bonpromotion
        - ps_bestsellers
        - bonbrand
        - bongdpr
        - bonnews
        - productbutton
        - boninstagram
      displayLeftColumn:
        - ps_facetedsearch
        - boninfoban
      displayOneClick:
        - bonorder
      displayPaymentReturn:
        - ps_checkpayment
        - ps_wirepayment
        - bongooglepay
      displayProductAdditionalInfo:
        - ps_sharebuttons
        - bonbrand
        - bongooglepay
      displayProductButton:
        - productbutton
      displayProductCountdownBlock:
        - productcountdown
      displayProductExtraContent:
        - boncomments
      displayProductListReviews:
        - boncomments
      displayProductPopup:
        - bontab
        - bonask
        - boncomments
      displayProductPriceBlock:
        - productcountdown
        - bonbrand
      displayProductPurchaseBlock:
        - productpurchase
      displayProductTab:
        - productyoutube
        - customtab
      displayProductTabContent:
        - productyoutube
        - customtab
      displayPromotion:
        - bonpromotion
      displayReassurance:
        - blockreassurance
      displayRightColumnProduct:
        - boncomments
      displaySearch:
        - ps_searchbar
      displayThumbnailsImage:
        - bonthumbnails
      displayTop:
        - ps_mainmenu
        - ps_customersignin
        - ps_shoppingcart
        - bonsearch
        - ps_languageselector
        - ps_currencyselector
        - bonwishlist
        - boncompare
      displayWrapperBottom:
        - bonnewsletter
        - bontheme
        - boncall
        - bonwhatsappchat
        - facebookwidget
  image_types:
    Brands:
      width: 300
      height: 195
      scope:
        - manufacturers
        - suppliers
    cart_default:
      width: 125
      height: 125
      scope:
        - products
    category_default:
      width: 141
      height: 141
      scope:
        - categories
    home_default:
      width: 560
      height: 560
      scope:
        - products
    large_default:
      width: 900
      height: 900
      scope:
        - products
        - manufacturers
        - suppliers
    medium_default:
      width: 452
      height: 452
      scope:
        - products
        - manufacturers
        - suppliers
    small_default:
      width: 98
      height: 98
      scope:
        - products
        - categories
        - manufacturers
        - suppliers
    stores_default:
      width: 396
      height: 396
      scope:
        - stores

theme_settings:
  default_layout: layout-full-width
  layouts:
    pagenotfound: layout-full-width
    best-sales: layout-full-width
    contact: layout-full-width
    index: layout-full-width
    manufacturer: layout-full-width
    new-products: layout-full-width
    password: layout-full-width
    prices-drop: layout-full-width
    sitemap: layout-full-width
    supplier: layout-full-width
    address: layout-full-width
    addresses: layout-full-width
    authentication: layout-full-width
    cart: layout-full-width
    discount: layout-full-width
    history: layout-full-width
    identity: layout-full-width
    my-account: layout-full-width
    order-follow: layout-full-width
    order-slip: layout-full-width
    order: layout-full-width
    search: layout-full-width
    stores: layout-full-width
    guest-tracking: layout-full-width
    order-confirmation: layout-full-width
    product: layout-full-width
    category: layout-left-column
    cms: layout-full-width
    module-cheque-payment: layout-full-width
    module-cheque-validation: layout-full-width
    module-bankwire-validation: layout-full-width
    module-bankwire-payment: layout-full-width
    module-cashondelivery-validation: layout-full-width
    module-ps_checkpayment-payment: layout-full-width
    module-ps_checkpayment-validation: layout-full-width
    module-ps_emailsubscription-verification: layout-full-width
    module-ps_emailsubscription-subscription: layout-full-width
    module-ps_faviconnotificationbo-AdminAjaxFaviconBO: layout-full-width
    module-ps_shoppingcart-ajax: layout-full-width
    module-ps_wirepayment-payment: layout-full-width
    module-ps_wirepayment-validation: layout-full-width
    module-psgdpr-AdminAjaxPsgdpr: layout-full-width
    module-psgdpr-AdminDownloadInvoicesPsgdpr: layout-full-width
    module-ps_checkout-AdminAjaxPrestashopCheckout: layout-full-width
    module-ps_checkout-AdminPaypalOnboardingPrestashopCheckout: layout-full-width
    module-boninstagramslick-instagram: layout-full-width
    module-bongooglemap-googlemap: layout-full-width

dependencies:
  modules:
    - bonask
    - bonattribute
    - bonbanner
    - bonbannermenu
    - bonbrand
    - boncall
    - boncart
    - boncollection
    - boncomments
    - boncompare
    - bongdpr
    - bongooglemap
    - bongooglepay
    - bonhtmlcontent
    - boninfoban
    - boninstagram
    - bonloginfacebook
    - bonnews
    - bonnewsletter
    - bonnotice
    - bonorder
    - bonportfolio
    - bonpromotion
    - bonsearch
    - bonslick
    - bontab
    - bontheme
    - bonthumbnails
    - bonwhatsappchat
    - bonwishlist
    - bonzoom
    - customtab
    - facebookwidget
    - productbutton
    - productcountdown
    - productpurchase
    - productyoutube
    - psgdpr
    - zendeskchat
